### ISSUE TITLE
index.js require problem

### ISSUE THREAD

**Issue by duncanmeech** [cymen/webfont-loader#1]
In index.js you require:

var fontObserver = require('font-face-observer');
....but then later in the file you execute:
return new FontFaceObserver(fontFamily, {weight: fontWeight}).check();
...This should be:
return new fontObserver(fontFamily, {weight: fontWeight}).check();

Strangely your version works in Chrome in our project but not in Safari or Firefox without the fix?

**Comment by cymen** [comment]
Odd -- looks like Justin fixes this on the forked version. I'll get that fix in.

**Comment by cymen** [comment]
And sorry for the slow response -- I missed the notification email.

**Comment by cymen** [comment]
I've pulled over the changes from teespring-webfont-loader. Thanks!
